[build]
  publish = "build"                    
  functions = "netlify/functions"      
  command = "npm run build"            

[dev]
  functions = "netlify/functions"       
  publish = "build"
  port = 8888                      
  targetPort = 3000                 

# Redirects
[[redirects]]
  from = "/api/*"                      
  to = "/.netlify/functions/:splat"   
  status = 200
  force = true